name: Sync Repository to Google Drive

on:
  push:
    branches:
      - main  # Cambia con "master" se il tuo branch principale si chiama master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Setup Rclone Config
        env:
          JSON_KEY: ${{ secrets.GDRIVE_SA_JSON }}
          FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$JSON_KEY" > ~/.config/rclone/sa.json
          cat <<EOF > ~/.config/rclone/rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = ~/.config/rclone/sa.json
          root_folder_id = $FOLDER_ID
          EOF

      - name: Sync to Google Drive
        run: |
          rclone sync . gdrive: \
            --exclude ".git/**" \
            --exclude ".github/**" \
            --drive-service-account-file ~/.config/rclone/sa.json \
            --drive-impersonate tua-email-google@gmail.com \
            -v
